/**
 * Import name and distribution name frequently disagree. The scanner supplies
 * the authoritative mapping when the analysing interpreter has the package
 * installed; this table covers the cases where it does not, so an uninstalled
 * checkout is still analysed correctly.
 */
export const IMPORT_ALIASES: Record<string, string[]> = {
  PIL: ['pillow'],
  yaml: ['pyyaml'],
  dateutil: ['python-dateutil'],
  bs4: ['beautifulsoup4'],
  cv2: ['opencv-python', 'opencv-python-headless'],
  sklearn: ['scikit-learn'],
  skimage: ['scikit-image'],
  dotenv: ['python-dotenv'],
  attr: ['attrs'],
  attrs: ['attrs'],
  jwt: ['pyjwt'],
  jose: ['python-jose'],
  serial: ['pyserial'],
  OpenSSL: ['pyopenssl'],
  Crypto: ['pycryptodome'],
  pkg_resources: ['setuptools'],
  MySQLdb: ['mysqlclient'],
  googleapiclient: ['google-api-python-client'],
  github: ['PyGithub'],
  pytest_cov: ['pytest-cov'],
  _pytest: ['pytest'],
  pytest_asyncio: ['pytest-asyncio'],
  psycopg: ['psycopg', 'psycopg-binary'],
  psycopg2: ['psycopg2', 'psycopg2-binary'],
  prometheus_client: ['prometheus-client'],
  grpc: ['grpcio'],
  kafka: ['kafka-python'],
  docker: ['docker'],
  numpy: ['numpy'],
  pandas: ['pandas'],
  ruamel: ['ruamel.yaml'],
  setuptools: ['setuptools'],
  mako: ['Mako'],
  pytz: ['pytz'],
  tzlocal: ['tzlocal'],
  win32com: ['pywin32'],
  lxml: ['lxml'],
  matplotlib: ['matplotlib'],
  seaborn: ['seaborn'],
  sqlalchemy: ['sqlalchemy', 'SQLAlchemy'],
  pydantic: ['pydantic'],
  fastapi: ['fastapi'],
  starlette: ['starlette'],
  uvicorn: ['uvicorn'],
  celery: ['celery'],
  redis: ['redis'],
  boto3: ['boto3'],
  botocore: ['botocore'],
  httpx: ['httpx'],
  aiohttp: ['aiohttp'],
  werkzeug: ['werkzeug'],
  flask: ['flask'],
  django: ['django'],
  jinja2: ['jinja2'],
  typer: ['typer'],
  click: ['click'],
  rich: ['rich'],
  tqdm: ['tqdm'],
};

/** Distributions that are normally invoked as a console script, not imported. */
export const CONSOLE_ONLY: Set<string> = new Set([
  'ruff',
  'mypy',
  'pyright',
  'ty',
  'pytest',
  'pytest-cov',
  'coverage',
  'pre-commit',
  'tox',
  'nox',
  'hatch',
  'hatchling',
  'build',
  'twine',
  'black',
  'isort',
  'flake8',
  'pylint',
  'sphinx',
  'mkdocs',
  'uvicorn',
  'gunicorn',
  'alembic',
  'celery',
  'honcho',
  'maturin',
  'setuptools-scm',
  'pip-audit',
  'bandit',
  'commitizen',
  'towncrier',
]);
